
cfg = dict(
    model_type='bisenetv1',
    n_cats=6,
    num_aux_heads=1,
    lr_start=1e-2,
    weight_decay=5e-4,
    warmup_iters=100,
    max_iter=300,
    dataset='CustomerDataset',
    im_root='./datasets/bad/imgroot',
    train_im_anns='./datasets/bad/train.txt',
    val_im_anns='./datasets/bad/val.txt',
    scales=[0.75, 2.],
    cropsize=[1024,960],
    eval_crop=[1024,960],
    eval_scales=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
    ims_per_gpu=2,
    eval_ims_per_gpu=1,
    use_fp16=True,
    use_sync_bn=False,
    respth='./res',
)
